name: "Git Log Action"
description: "Saves Git Log Data in GitHub Workflow"
author: "jarrodparkes"
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  start:
    description: "Start Git commit object (e.g. SHA, tag, branch name) in revision range"
    required: true
  end:
    description: "End Git commit object (e.g. SHA, tag, branch name) in revision range"
    required: true
outputs:
  log:
    description: "Output of Git Log"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.start }}
    - ${{ inputs.end }}
