name: "Git Log Action"
description: "Saves Git Log Data in GitHub Workflow"
author: "jarrodparkes"
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  commit:
    description: "Specify Git commit (e.g. SHA, tag, branch name)"
    required: false
outputs:
  log:
    description: "Output of Git Log"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.commit }}
